AllCops:
  TargetRubyVersion: 2.4
  Exclude:
  - db/**/*
  - bin/**/*
  - vendor/**/*
  DisplayCopNames: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 100

Documentation:
    Enabled: false
