# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 79d488f786e11deaf6828a95cacef054c652492b8cba69a895530a96aab18ed69a693030d484f2220a2d8225281df44649308ba5977aedfebe43f4cd08fad14c

test:
  secret_key_base: 3e09ca1c17f42d39e94bee8b37d4400e94edf07f09a67988e0c0c628ca20f4dede7c4d381ec6a1ef8d70be96c8900c20c104b70b24c612789465ab239ca8499c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
